steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${_TAG}', '-f', 'apps/api/Dockerfile', '/']
  automapSubstitutions: true

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${_TAG}']
  automapSubstitutions: true

substitutions:
  _IMAGE_NAME: 'transcript-seeker-api'
  _TAG: 'latest'
