steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        gcr.io/$PROJECT_ID/github.com/GITHUB_USERNAME/turborepo-cloud-run-docs-prod:$COMMIT_SHA
      - '-f'
      - apps/docs/Dockerfile
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        gcr.io/$PROJECT_ID/github.com/GITHUB_USERNAME/turborepo-cloud-run-docs-prod:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=gcr.io/$PROJECT_ID/github.com/GITHUB_USERNAME/turborepo-cloud-run-docs-prod:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    gcr.io/$PROJECT_ID/github.com/GITHUB_USERNAME/turborepo-cloud-run-docs-prod:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: docs-prod
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
