packages:
  - packages/*
  - apps/*
  - tooling/*

catalog:
  eslint: ^9.12.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8
  dotenv-cli: ^7.4.2
  axios: ^1.7.2

catalogs:
  react19:
    react: rc
    react-dom: rc
    "@types/react": npm:types-react@rc
    "@types/react-dom": npm:types-react@rc